// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Oscilline contributors
//
// The slot table and the character-clip name tokens.

#include "oscilline/asset/map.hpp"

#include "oscilline/course/obstacle.hpp"

namespace oscilline {
namespace {

// The only event-to-asset table. Evidence is the note on each row:
// name (folder or file name), format (counts and layout), or emulator
// (black-box observation). Boot-logo images are intentionally absent.
constexpr MapRow kMap[] = {
    {Slot::FormBase,
     "form.base",
     AssetKind::Model,
     AssetArea::GamePak,
     AssetPick::FolderModel,
     "CHARA/PEELOO",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: gameplay model folder CHARA/PEELOO"},
    {Slot::FormDegradedA,
     "form.degraded-a",
     AssetKind::Model,
     AssetArea::GamePak,
     AssetPick::FolderModel,
     "CHARA/FROG",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: first degraded form folder CHARA/FROG"},
    {Slot::FormDegradedB,
     "form.degraded-b",
     AssetKind::Model,
     AssetArea::GamePak,
     AssetPick::FolderModel,
     "CHARA/SNAKE",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: second degraded form folder CHARA/SNAKE"},
    {Slot::FormUpgraded,
     "form.upgraded",
     AssetKind::Model,
     AssetArea::GamePak,
     AssetPick::FolderModel,
     "CHARA/SUPER",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: upgraded form folder CHARA/SUPER"},
    {Slot::Font,
     "font",
     AssetKind::Font,
     AssetArea::GamePak,
     AssetPick::LanguageFont,
     "FONT/FE_FONT.TMD",
     "FONT/01_FONT.TMD",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: FONT/FE_FONT.TMD, or FONT/01_FONT.TMD on a Japanese archive"},
    {Slot::RankMarks,
     "rank.marks",
     AssetKind::Font,
     AssetArea::GamePak,
     AssetPick::Exact,
     "FONT/MARK.TMD",
     "",
     0,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: FONT/MARK.TMD exists; which object is which mark is still open"},
    {Slot::ScoreCoupons,
     "score.coupons",
     AssetKind::Meter,
     AssetArea::GamePak,
     AssetPick::Exact,
     "FONT/MARK.TMD",
     "METERS/SCORE.ANM",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Format,
     "format: fifteen ordered coupon objects and a 240-frame single-object carousel track"},
    {Slot::MeterProgress,
     "meter.progress",
     AssetKind::Meter,
     AssetArea::GamePak,
     AssetPick::FolderPair,
     "METERS",
     "",
     0,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Emulator,
     "emulator: the SPEED.TMD candidate does not match the full-width progress arc"},
    {Slot::MeterEvolution,
     "meter.evolution",
     AssetKind::Meter,
     AssetArea::GamePak,
     AssetPick::FolderPair,
     "METERS",
     "",
     1,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: next METERS pair; emulator check still open, so this stays off"},
    {Slot::MeterSpeed,
     "meter.speed",
     AssetKind::Meter,
     AssetArea::GamePak,
     AssetPick::FolderPair,
     "METERS",
     "",
     2,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: third METERS pair; emulator check still open, so this stays off"},
    {Slot::RoundCaption,
     "round.caption",
     AssetKind::Meter,
     AssetArea::GamePak,
     AssetPick::FolderPair,
     "MESSAGE",
     "",
     0,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: MESSAGE candidate; the PAL pick is DEMO.TMD, not a verified round caption"},
    {Slot::ResultsDigits,
     "results.digits",
     AssetKind::Font,
     AssetArea::GamePak,
     AssetPick::Exact,
     "RESULT/DIGIT.TMD",
     "",
     0,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: guessed results digit model; off until the path is confirmed"},
    {Slot::MenuModel,
     "menu.model",
     AssetKind::MenuModel,
     AssetArea::GamePak,
     AssetPick::FolderTmd,
     "TITLE/VIBRI",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Visual,
     "visual: on-disc TITLE/VIBRI menu model; playback checked against the original"},
    {Slot::MenuWheel,
     "menu.wheel",
     AssetKind::MenuModel,
     AssetArea::GamePak,
     AssetPick::FolderTmd,
     "MENU/WHEEL",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Name,
     "name guess: MENU/WHEEL may be the title wheel; off until a listing confirms it"},
    {Slot::MenuLabels,
     "menu.labels",
     AssetKind::MenuModel,
     AssetArea::GamePak,
     AssetPick::FolderTmd,
     "MENU/LABEL",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Name,
     "name guess: MENU/LABEL may be localized menu words; off until a language archive confirms "
     "it"},
    {Slot::CameraRoad,
     "camera.road",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/B01.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/B01.ANC is the in-play camera on course 4, stretched across each section"},
    {Slot::CameraIntro,
     "camera.intro",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/TV_SS.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/TV_SS.ANC is the S-camera transition, including the course intro"},
    {Slot::CameraPlay,
     "camera.play",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/S01.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/S01.ANC is an in-play camera, 26 keys stretched across its section"},
    {Slot::CameraS02,
     "camera.s02",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/S02.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/S02.ANC is an in-play camera, 780 keys stretched across its section"},
    {Slot::CameraTvBb,
     "camera.tv-bb",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/TV_BB.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/TV_BB.ANC is the B-camera transition, 240 keys at 30 per second"},
    {Slot::CameraTvBs,
     "camera.tv-bs",
     AssetKind::CameraPath,
     AssetArea::GamePak,
     AssetPick::Exact,
     "ROAD/TV_BS.ANC",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Emulator,
     "emulator: ROAD/TV_BS.ANC is the S/B transition, 240 keys at 30 per second"},
    {Slot::CameraMenu,
     "camera.menu",
     AssetKind::CameraPath,
     AssetArea::TitlePak,
     AssetPick::FolderSuffix,
     "CAM",
     ".ANC",
     0,
     -1,
     -1,
     Confidence::Medium,
     Evidence::Name,
     "name: TITLE/CAM folder; exact file unverified, so this stays off"},
    {Slot::SoundBankGame,
     "sound.bank.game",
     AssetKind::SoundBank,
     AssetArea::GameAudio,
     AssetPick::AudioStem,
     "GAME/AUDIO/PSJ_SE",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: game audio folder, one VH/VB pair"},
    {Slot::SoundBankTitle,
     "sound.bank.title",
     AssetKind::SoundBank,
     AssetArea::TitleAudio,
     AssetPick::AudioStem,
     "TITLE/AUDIO/TITLE",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: TITLE/AUDIO/TITLE.VH and TITLE.VB on the PAL disc"},
    {Slot::SoundBankTutorial,
     "sound.bank.tutorial",
     AssetKind::SoundBank,
     AssetArea::TutorialAudio,
     AssetPick::AudioStem,
     "KIOSK/AUDIO/KIOSK",
     "",
     0,
     -1,
     -1,
     Confidence::High,
     Evidence::Name,
     "name: KIOSK/AUDIO/KIOSK.VH and KIOSK.VB on the PAL disc"},
    // Event rows stay silent. Program and note are unset until a capture
    // matches them. Evidence: emulator, still open.
    {Slot::SoundMenuMove,
     "sound.menu-move",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: menu move, unmatched"},
    {Slot::SoundConfirm,
     "sound.confirm",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: confirm, unmatched"},
    {Slot::SoundBack,
     "sound.back",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: back, unmatched"},
    {Slot::SoundBlock,
     "sound.block",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: block, unmatched"},
    {Slot::SoundLoop,
     "sound.loop",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: loop, unmatched"},
    {Slot::SoundWave,
     "sound.wave",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: wave, unmatched"},
    {Slot::SoundPit,
     "sound.pit",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: pit, unmatched"},
    {Slot::SoundPerfect,
     "sound.perfect",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: perfect, unmatched"},
    {Slot::SoundGood,
     "sound.good",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: good, unmatched"},
    {Slot::SoundMiss,
     "sound.miss",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: miss, unmatched"},
    {Slot::SoundDamage,
     "sound.damage",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: damage, unmatched"},
    {Slot::SoundForm,
     "sound.form",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: form change, unmatched"},
    {Slot::SoundTally,
     "sound.tally",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: results tally, unmatched"},
    {Slot::SoundRound,
     "sound.round",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: round start, unmatched"},
    {Slot::SoundAmbient,
     "sound.ambient",
     AssetKind::Sound,
     AssetArea::None,
     AssetPick::None,
     "",
     "",
     0,
     -1,
     -1,
     Confidence::Low,
     Evidence::Emulator,
     "emulator: ambient loop, unmatched"},
};

} // namespace

std::string_view evidence_name(Evidence evidence) {
    switch (evidence) {
    case Evidence::Name:
        return "name";
    case Evidence::Format:
        return "format";
    case Evidence::Emulator:
        return "emulator";
    case Evidence::Visual:
        return "visual";
    }
    return "name";
}

// Action letters and idle words. Longer words are listed before the single
// letters they start with. The matcher still picks the longest token, so
// WAIT stays idle and does not become wave. Every token is high. J, L, and W
// were observed on a real clear. H was checked by eye against the original.
// Pairs, trailing _F whiffs, and MISS stay at that high confidence;
// see match_character_clip. SUPER is a form folder, not a clip token, and
// does not match.
constexpr ClipToken kClipTokens[] = {
    {"BLOCK",
     kActionBlock,
     ClipKind::Action,
     Confidence::High,
     Evidence::Name,
     "name: stem BLOCK is the block obstacle"},
    {"PIT",
     kActionPit,
     ClipKind::Action,
     Confidence::High,
     Evidence::Name,
     "name: stem PIT is the pit obstacle"},
    {"LOOP",
     kActionLoop,
     ClipKind::Action,
     Confidence::High,
     Evidence::Name,
     "name: stem LOOP is the loop obstacle"},
    {"WAVE",
     kActionWave,
     ClipKind::Action,
     Confidence::High,
     Evidence::Name,
     "name: stem WAVE is the wave obstacle"},
    {"IDLE",
     0,
     ClipKind::Idle,
     Confidence::High,
     Evidence::Name,
     "name: stem IDLE is the idle cycle"},
    {"WAIT",
     0,
     ClipKind::Idle,
     Confidence::High,
     Evidence::Name,
     "name: stem WAIT is the idle cycle"},
    {"SKIP",
     0,
     ClipKind::Idle,
     Confidence::High,
     Evidence::Name,
     "name: stem SKIP, including a numbered N##_SKIP file, is the idle cycle"},
    {"MISS",
     0,
     ClipKind::Miss,
     Confidence::High,
     Evidence::Visual,
     "visual: stem MISS is a failed action"},
    {"B",
     kActionBlock,
     ClipKind::Action,
     Confidence::High,
     Evidence::Name,
     "name: letter B is block"},
    {"P", kActionPit, ClipKind::Action, Confidence::High, Evidence::Name, "name: letter P is pit"},
    {"L",
     kActionLoop,
     ClipKind::Action,
     Confidence::High,
     Evidence::Emulator,
     "emulator: L plays on a real loop clear"},
    {"W",
     kActionWave,
     ClipKind::Action,
     Confidence::High,
     Evidence::Emulator,
     "emulator: W plays on a real wave clear"},
    {"J",
     kActionBlock,
     ClipKind::Action,
     Confidence::High,
     Evidence::Emulator,
     "emulator: J plays on a real block clear"},
    {"H",
     kActionPit,
     ClipKind::Action,
     Confidence::High,
     Evidence::Visual,
     "visual: H checked by eye against the original, not by emulator capture"},
};

std::span<const MapRow> asset_map() {
    return kMap;
}

std::span<const ClipToken> character_clip_tokens() {
    return kClipTokens;
}

const MapRow* map_row(Slot slot) {
    for (const MapRow& row : kMap) {
        if (row.slot == slot) {
            return &row;
        }
    }
    return nullptr;
}

} // namespace oscilline
